### ISSUE TITLE
Propose criteria/mechanism for clubs to request pizza/coffee money

### ISSUE THREAD

**Issue by m-branson** [mozilla/OSSN#1]
- [x] Draft a proposal
- [x] Get feedback from @bacharakis 
- [x] Create a form for requesting pizza money @LucyeoH

**Comment by LucyeoH-zz** [comment]
@bacharakis please review https://docs.google.com/document/d/1s_k-VLR0mlnjYVqui1ZMZ6UaQU7qW_kQxcFmDBufcl4/edit# there are a number of options that we can discuss in our meeting tomorrow.

**Comment by LucyeoH-zz** [comment]
Decision made! We'll be sharing pizza money out starting this week
