### ISSUE TITLE
OSSN Summit: Phase 1 logistics

### ISSUE THREAD

**Issue by bacharakis** [mozilla/OSSN#139]
### Action items
- [x] Identify a hotel (Lucy)
- [x] identify a catering (Lucy)
- [x] Bring Kiki onboard (Christos)
- [x] Send an email to students for next steps (Christos)

### Links/resources
any relevant links/resources

**Comment by bacharakis** [comment]
Hotel reccomendations:
- http://citystation.mycollegesuites.com/
- Hilton Troy
- Best Western Troy

**Comment by LucyeoH-zz** [comment]
Tuesday June 19th: 
- [x] Get quotes from 3 hotels (choose one if possible & reserve 16 rooms) 
- [ ] Email Ada re: catering re: restaurants 
- [ ] Get Egencia set up for volunteers
- [x] Send "info" doc to Christos/update account myself
