### ISSUE TITLE
Community Manager Onboarding week 1

### ISSUE THREAD

**Issue by bacharakis** [mozilla/OSSN#198]
### Action items
- [x] Connect calendly with gcalendar
- [x] Go through and organize gdrive
- [x] Intro email to OSSN mailing list
- [x] Say hi on OSSN Slack
- [x] Write the OSSN wiki page

### Links/resources
any relevant links/resources

**Comment by csrs** [comment]
Wiki  page draft: 
https://docs.google.com/document/d/1TEiBQjiwoGGitRQ5hX6j9lD1f-WshmYtgKApTJ3zCAQ/edit

**Comment by csrs** [comment]
Wiki page: https://wiki.mozilla.org/Open_Source_Student_Network
