### ISSUE TITLE
Canned response for first email to new clubs

### ISSUE THREAD

**Issue by csrs** [mozilla/OSSN#204]
Estimate: 1 hr (.5 write, .5 revise)

### Action items
- [x] Write canned response
- [x] Draft an invitation to join the network

### Links/resources

https://docs.google.com/document/d/1Bj-5Vn5uP92B33Nl4KBRof7M7DsCINpeftytt9W9xYE/edit

**Comment by csrs** [comment]
@bacharakis I updated the invitation

**Comment by bacharakis** [comment]
Reviewed! Thank you
