### ISSUE TITLE
Club Recruitment

### ISSUE THREAD

**Issue by bacharakis** [mozilla/OSSN#205]
Estimate: 6 hours (2: Mailchimp and mailing list, 2: follow up emails, 1: scheduling 1:1s, 1: clean up email list)

### Action items
- [x] Create Mailchimp lists
- [x] Send emails to identified Clubs
- [x] Schedule 1:1 
- [x] Cleanup email list
- [ ] Reach out to POSSE - christos
- [ ] Reach out to Ladies Storm Hackathons FB group - christos
- [x] Reach out to ChickTech - catherine 

### Links/resources
any relevant links/resources

**Comment by csrs** [comment]
Invites sent July 10, July 17, July 29, Aug 12 (A/B), Aug 28 (Git September)


Emails are drafted, different emails for different types of clubs.

Some clubs only have mailing lists that I'll need to join.

Status of which clubs have joined: https://docs.google.com/spreadsheets/d/143-WQoGSMb5cvPIMUTkq-EHadI0FoIeIKA078w47sr0/edit#gid=0

**Comment by csrs** [comment]
Waiting to be added to mailing lists for Stanford and UNC Chapel Hill. All other clubs have been contacted.

**Comment by csrs** [comment]
@bacharakis There is a tab now for communities to reach out to. https://docs.google.com/spreadsheets/d/143-WQoGSMb5cvPIMUTkq-EHadI0FoIeIKA078w47sr0/edit#gid=0

**Comment by bacharakis** [comment]
@bacharakis to reach out to POSSE
