### ISSUE TITLE
Git September resources: materials for clubs

### ISSUE THREAD

**Issue by csrs** [mozilla/OSSN#225]
### Description (what is the goal of this issue)

Goal: All the students have at least a basic understanding of git (they have forked, cloned, and created a pull request)
How: Provide Clubs all the necessary resources for teaching their members git
When: September (4 weeks)

Materials for clubs: 
- Curriculum: GitHub flow (high level overview, then nitty gritty details)
- Curriculum: Common issues and how to overcome them
- Curriculum: Best practices and how to run workshops
- Activities
- Post-event Survey for club events
- Stickers 

### Action items
- [x] Curriculum: GitHub flow (high level overview, then nitty gritty details) - catherine [2]
- [x] Curriculum: Common issues and how to overcome them - catherine [2]
  - [x] Ask network for their suggestions
- [x] Curriculum: Best practices and how to run workshops - catherine [2]
- [ ] Activities 
  - [x] Add your name to the visual network graph [3]
  - [ ] Make a github pages site
- [x] Post-event survey for clubs - christos 
- [x] Stickers - christos
- [x] Update club list on pizza request form - catherine

### Links/resources
Planning doc: https://docs.google.com/document/d/1uwUXqafwo2SmRrrODxaJqnFzo45kUNeOb1kfiMUA2ns/edit#
[2] Curriculum doc: https://docs.google.com/document/d/1dzwQPLtYhoYAT1__ayznkzH99xrfp-MDs6phZ7H3UGI/edit#
[3] Visual network repo https://github.com/ossn/network

**Comment by bacharakis** [comment]
Christos to review and updated materials by Aug 20th
