### ISSUE TITLE
Run Q1 NPS Survey 

### ISSUE THREAD

**Issue by LucyeoH** [mozilla/OSSN#39]

**Comment by bacharakis** [comment]
Earlier this year we send this [feedback form](https://www.surveygizmo.com/s3/4121281/OSSN-Feedback-form) to our OSSN members.

Based on their feedback, our NPS score is: 83.3
They also gave us a clear picture on the things we need to prioritize for. You can [find the full report here](https://data.surveygizmo.com/r/28049_5a79ae279c6041.54501984)
