### ISSUE TITLE
Poster tool to make postering easier

### ISSUE THREAD

**Issue by m-branson** [mozilla/OSSN#4]
- [x] Create a list of tools for potential use - Rina ( @flekkowich                         )                        
- [] Assessing the tools they are out there (integrate with CoSS vs silo) - @a-kilroy

**Comment by flekkowich** [comment]
https://docs.google.com/spreadsheets/d/1RC7RlM17XPYTo6sPfzdLkAc-1aSTo8TDgD_qw7irBuQ/edit?usp=sharing

Tool overview here.

**Comment by bacharakis** [comment]
Tagging @a-kilroy

**Comment by a-kilroy** [comment]
Totally agree with @flekkowich suggestion. Piktochart seems like a great fit.
