### ISSUE TITLE
Sprint Cacciatore

### ISSUE THREAD

**Issue by bacharakis** [mozilla/OSSN#68]
-  Establishing infrastructure for the first 2 experiments
  -  Publish the survey
  -  Do external research for identifying relevant findings around our experiments
  -  Draft a proposal on pizza money
  -  Draft a proposal for providing access to speakers for our Clubs
  -  Identify a platform for posters creation
  -  Draft club meeting best practices and how-to
  -  Explore whether there is a component for showcasing our activities on the website
  -  Setup the GSoC platform
  -  Mask open source training under a mozilla community URL

**Comment by hmitsch** [comment]
@bacharakis I am worried that the GSoC hosting will not be as simple as we would like it to be. :-(

**Comment by bacharakis** [comment]
@hmitsch thanks for the update. Is there a way that I can help?

**Comment by hmitsch** [comment]
If you can provide docker containers, that would be awesome.

**Comment by a-kilroy** [comment]
Here is the relevant ticket from Yousef https://app.zenhub.com/workspace/o/mozilla/coss/issues/760
