### ISSUE TITLE
Plan and run February community call

### ISSUE THREAD

**Issue by bacharakis** [mozilla/OSSN#81]
### Action items
- [x] Doodle time 
- [x] Send invitation
- [x] Draft agenda
- [x] Run the call
- [x] Gather and process feedback 

### Links/resources
any relevant links/resources

**Comment by bacharakis** [comment]
Super exciting call! 

We gathered a lot of resources on how each club is doing elections and onboarding new members.
We also talked about speakers what students prefer (high profile speakers VS tech speakers delivering technical workshops).

Another call will be scheduled to dive more into the speakers topic. You can find all the meeting minutes [in this doc](https://docs.google.com/document/d/1fUp3brNpJTca-kkFJy5Av4M4Utad4-duivYCgl-I7wo/edit#)

**Comment by LucyeoH-zz** [comment]
Post-Call 
- [ ] Put recordings on site
- [ ] Put debrief on discourse
