### ISSUE TITLE
Intergrate a discourse category to the OSSN website

### ISSUE THREAD

**Issue by bacharakis** [mozilla/OSSN#83]
### Description (what is the goal of this issue)
We want to showcase activity on the OSSN website by integrating a discourse category where we will post information about our community calls, updates etc.

### Action items
- [x] identify timeline and technical requirements for that integration 
- [x] Draft a quick 2 months communication strategy on the posts we will communicate/publish in this category

### Links/resources
any relevant links/resources

**Comment by LucyeoH-zz** [comment]
Cross-post announcement for community call (Feb?)?

**Comment by LucyeoH-zz** [comment]
BLOCKED - by resource deprivation :(

**Comment by bacharakis** [comment]
Still blocked by P&E, moving to eggplant sprint
