### ISSUE TITLE
First Test of Pizza Money Pilot 

### ISSUE THREAD

**Issue by LucyeoH-zz** [mozilla/OSSN#89]
### Description (what is the goal of this issue)
To test the implementation of the pizza money pilot by distributing our first funds!

### Action items
- [x] Talk to Konstantina about moco pay pal
- [x] Test sending money with Kiki
- [ ] Request feedback from student

### Links/resources
any relevant links/resources

**Comment by bacharakis** [comment]
@LucyeoH can you please update the status of this issue for this sprint and then close it?

Thank you

**Comment by LucyeoH-zz** [comment]
Pizza money sent to the 2 people who requested it via Pizza Hut. 

I'm soliciting feedback about the process through [this form ](https://goo.gl/forms/5kez07UVJdvuyP2f2)but will ping again in 1 month (after they're more likely to have tried to use it).
