### ISSUE TITLE
Access to speakers: get feedback on our approach from 80% or for our Clubs (Lucy, Christos)

### ISSUE THREAD

**Issue by LucyeoH-zz** [mozilla/OSSN#90]
### Description (what is the goal of this issue)
Test our questions about students and speakers by talking to the students. 

### Action items
- [x] Surface questions in the next community call
- [ ] Translate feedback into next steps

### Links/resources
any relevant links/resources

**Comment by bacharakis** [comment]
We've gathered feedback a-sync from only the 40% of our network.
Unfortunately we didn't manage schedule a community call in this sprint, however we have already scheduled one for the next one.
